### ISSUE TITLE
many pictures for matlabPyrTools/TUTORIALS/matlabPyrTools.html are missing

### ISSUE THREAD

**Issue by HonghuiWang** [LabForComputationalVision/matlabPyrTools#2]
if open the matlabPryTools.html you can find many pictures are missing!
such as matlabPyrTools_12.png

**Comment by LabForComputationalVision** [comment]
The html pages look for the images in the 'HTML' subdirectory.  If you're just downloading the web pages you'll need that subdirectory as well.
